# Generated by Django 4.2 on 2023-04-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='sorting/images/')),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
